Repository ChrisCarini/intellij-platform-plugin-verifier-action, pull requests merged in 2024-07, with the labels that each got.

#80 Add dependabot to ChrisCarini/intellij-platform-plugin-verifier-action
  .github/dependabot.yml
  .github/workflows/dependabot-auto-merge.yml
Labels: size/M, repo-file-sync

#77 #76 Adds support for mute args
  README.md
  action.yml
  entrypoint.sh
Labels: size/M

#82 Adding retry logic for all `curl` calls with more explicit error handling for each.
  entrypoint.sh
Labels: size/L
